import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import type { ItineraryData } from './ItineraryPlanner';

// Clean, modern style definitions mimicking the beautiful UI
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 40,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    borderBottomWidth: 2,
    borderBottomColor: '#2563EB',
    paddingBottom: 15,
    marginBottom: 15,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  destinationLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#2563EB',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  dateRow: {
    flexDirection: 'row',
    color: '#64748B',
    fontSize: 12,
  },
  daySection: {
    marginBottom: 30,
  },
  dayHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 12,
    backgroundColor: '#F8FAFC',
    padding: 12,
    borderRadius: 6,
  },
  dayDate: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0F172A',
    marginRight: 10,
  },
  dayTheme: {
    fontSize: 14,
    color: '#64748B',
    fontStyle: 'italic',
  },
  activityRow: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingLeft: 10,
    borderLeftWidth: 2,
    borderLeftColor: '#E2E8F0',
  },
  activityTimeCol: {
    width: '18%',
    paddingRight: 10,
  },
  activityTime: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#475569',
  },
  activityContentCol: {
    width: '82%',
  },
  activityTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 4,
  },
  activityMetaRow: {
    flexDirection: 'row',
    marginTop: 2,
  },
  activityLocation: {
    fontSize: 10,
    color: '#2563EB',
  },
  activityNotes: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 3,
  },
  emptyText: {
    fontSize: 11,
    color: '#94A3B8',
    fontStyle: 'italic',
    paddingLeft: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#CBD5E1',
    fontSize: 10,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    paddingTop: 10,
  }
});

export default function ItineraryPDFDocument({ data }: { data: ItineraryData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.headerTop}>
            <Text style={styles.title}>{data.tripTitle || 'My Magnificent Itinerary'}</Text>
            {data.destination && (
              <Text style={styles.destinationLabel}>{data.destination}</Text>
            )}
          </View>
          <View style={styles.dateRow}>
            <Text>
              {data.startDate} {data.startDate && data.endDate ? ' to ' : ''} {data.endDate}
            </Text>
          </View>
        </View>

        {/* Days */}
        {data.days.map((day) => (
          <View key={day.id} style={styles.daySection} wrap={false}>
            <View style={styles.dayHeaderRow}>
              <Text style={styles.dayDate}>{day.date || 'Unnamed Day'}</Text>
              {day.theme && <Text style={styles.dayTheme}>— {day.theme}</Text>}
            </View>

            {day.activities.length === 0 ? (
              <Text style={styles.emptyText}>No activities arranged for this day.</Text>
            ) : (
              day.activities.map((activity) => (
                <View key={activity.id} style={styles.activityRow}>
                  <View style={styles.activityTimeCol}>
                    <Text style={styles.activityTime}>{activity.time || '--:--'}</Text>
                  </View>
                  <View style={styles.activityContentCol}>
                    <Text style={styles.activityTitle}>{activity.title || 'Untitled Activity'}</Text>
                    {activity.location && (
                      <Text style={styles.activityLocation}>📍 {activity.location}</Text>
                    )}
                    {activity.notes && (
                      <Text style={styles.activityNotes}>{activity.notes}</Text>
                    )}
                  </View>
                </View>
              ))
            )}
          </View>
        ))}

        {/* Footer info */}
        <Text style={styles.footer} fixed>
          Generated by Udream Travel Planner
        </Text>
      </Page>
    </Document>
  );
}
